### ISSUE TITLE
Sections are big and empty.

### ISSUE THREAD

**Issue by geohacker** [hasgeek/rootconf#12]
Every section eats up a lot of space and there's no content. Reduce the size may be?

**Comment by jace** [comment]
They should be three columns. There isn't much text to make them full width.

**Comment by sevenaces** [comment]
Fixed. Would upload on next commit with other fixes.

**Comment by jace** [comment]
Commit every fix when you fix it so that you have a commit trail showing when anything changed. Helps make it easier to identify the source of regressions.

**Comment by sevenaces** [comment]
Alright. Will do.
