### ISSUE TITLE
SponsorKit should be hosted on website

### ISSUE THREAD

**Issue by jace** [hasgeek/rootconf#13]
Let the sponsorship link lead straight to the document. Host it in the `/static` folder. Don't recommend emailing. The sponsor document is in Dropbox.

**Comment by sevenaces** [comment]
Can we put up the sponsor kit on slideshare or something instead? Always better to show it online than to have them download it?

**Comment by jace** [comment]
It'll be HTML in future. PDF for now should do. Another 2-3 events to go, max.

**Comment by sevenaces** [comment]
Alright. Will just put it.
